### PR TITLE
Set outdir in tsconfig.json

### PR DESCRIPTION
**Pull request by jamie-pate**
Due to the way that typescript works in nodejs module resolution, the
index.d.ts file will load .ts files incorrectly if you publish the .js
and .d.ts files in alongside the .ts files.

Unfortunately this causes my version of typescript to attempt to compile
the module's .ts files which are not working with typescript 4.4.3!

See microsoft/TypeScript#10704 which considers
this to be 'working as intended'

The solution is to avoid outputting your .js and .d.ts files into the
same location as the .ts files.

Unfortunately, adding 'dist/index.d.ts' to the types in the package.json
caused all imports of '..' (pointing to the /index.ts file) to trigger
this issue:
microsoft/TypeScript#14538 (comment)
which I solved by changing those to '../index' or '../../index' etc.

Here is the error I get while trying to compile my project which uses
"typescript": "^4.4.3" after `npm install typed-cli:

```
node_modules/typed-cli/src/pipeline.ts:23:9 - error TS2322: Type
'unknown' is not assignable to type 'Error | undefined'.
  Type 'unknown' is not assignable to type 'Error'.

23         return e;
           ~~~~~~~~~

Found 1 error.
```

### CODE REVIEW

**Comment by int0h** [comment]
I excluded `.ts` files from `npm` package. Check out branch `refresh` and version `^1.1.0-rc`

**Comment by int0h** [comment]
tell me if https://github.com/int0h/typed-cli/commit/7e9516932039d584be1199e2687ee538af76d93e this is fixed now as well

**Comment by jamie-pate** [comment]
Fixed in 1.1.0-rc
